version: "3.8"

services:
  mlflow-recommender:
    build:
      context: .
    platform: linux/amd64
    container_name: mlflow-service
    ports:
      - "5001:5001"
    networks:
      - ecommerce-analytics-network
    restart: unless-stopped
    volumes:
      - mlflow-db:/code/mlruns       # named volume
      - ./mlflow.db:/code/mlflow.db  # bind mount local file

networks:
  ecommerce-analytics-network:
    driver: bridge

volumes:
  mlflow-db: