export interface Product {
    id: number
    name: string
    price: number
    originalPrice?: number
    image: string
    category: string
    rating: number
    reviews: number
    description?: string
  }
  
  export const products: Product[] = [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 199.99,
      originalPrice: 249.99,
      image: "/images/products/wireless-headphones.png",
      category: "Electronics",
      rating: 4.5,
      reviews: 128,
      description: "Premium wireless headphones with noise cancellation and 30-hour battery life.",
    },
    {
      id: 2,
      name: "Smart Watch",
      price: 299.99,
      originalPrice: 399.99,
      image: "/images/products/smart-watch.png",
      category: "Electronics",
      rating: 4.8,
      reviews: 89,
      description: "Advanced smartwatch with health monitoring, GPS, and 7-day battery life.",
    },
    {
      id: 3,
      name: "Designer Jacket",
      price: 159.99,
      originalPrice: 199.99,
      image: "/images/products/designer-jacket.png",
      category: "Fashion",
      rating: 4.3,
      reviews: 67,
      description: "Stylish designer jacket made from premium materials with modern fit.",
    },
    {
      id: 4,
      name: "Coffee Maker",
      price: 89.99,
      originalPrice: 119.99,
      image: "/images/products/coffee-maker.png",
      category: "Home & Garden",
      rating: 4.6,
      reviews: 234,
      description: "Professional-grade coffee maker with programmable settings and thermal carafe.",
    },
    {
      id: 5,
      name: "Gaming Mouse",
      price: 79.99,
      originalPrice: 99.99,
      image: "/images/products/gaming-mouse.png",
      category: "Gaming",
      rating: 4.7,
      reviews: 156,
      description: "High-precision gaming mouse with customizable RGB lighting and 16000 DPI sensor.",
    },
    {
      id: 6,
      name: "Bluetooth Speaker",
      price: 49.99,
      originalPrice: 69.99,
      image: "/images/products/bluetooth-speaker.png",
      category: "Electronics",
      rating: 4.4,
      reviews: 92,
      description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    },
    {
      id: 7,
      name: "Running Shoes",
      price: 129.99,
      originalPrice: 159.99,
      image: "/images/products/running-shoes.png",
      category: "Fashion",
      rating: 4.5,
      reviews: 178,
      description: "Lightweight running shoes with advanced cushioning and breathable mesh upper.",
    },
    {
      id: 8,
      name: "Desk Lamp",
      price: 39.99,
      originalPrice: 54.99,
      image: "/images/products/desk-lamp.png",
      category: "Home & Garden",
      rating: 4.2,
      reviews: 43,
      description: "Adjustable LED desk lamp with touch controls and USB charging port.",
    },
    {
      id: 9,
      name: "Mechanical Keyboard",
      price: 149.99,
      originalPrice: 179.99,
      image: "/images/products/mechanical-keyboard.png",
      category: "Electronics",
      rating: 4.6,
      reviews: 201,
      description: "Premium mechanical keyboard with tactile switches and customizable backlighting.",
    },
    {
      id: 10,
      name: "Yoga Mat",
      price: 29.99,
      originalPrice: 39.99,
      image: "/images/products/yoga-mat.png",
      category: "Sports",
      rating: 4.3,
      reviews: 87,
      description: "Non-slip yoga mat with extra cushioning and eco-friendly materials.",
    },
    {
      id: 11,
      name: "Wireless Charger",
      price: 34.99,
      originalPrice: 49.99,
      image: "/images/products/wireless-charger.png",
      category: "Electronics",
      rating: 4.1,
      reviews: 156,
      description: "Fast wireless charger compatible with all Qi-enabled devices.",
    },
    {
      id: 12,
      name: "Backpack",
      price: 79.99,
      originalPrice: 99.99,
      image: "/images/products/backpack.png",
      category: "Fashion",
      rating: 4.4,
      reviews: 123,
      description: "Durable travel backpack with laptop compartment and water-resistant fabric.",
    },
    {
      id: 13,
      name: "Smartphone",
      price: 699.99,
      originalPrice: 799.99,
      image: "/images/products/smartphone.png",
      category: "Electronics",
      rating: 4.7,
      reviews: 342,
      description: "Latest smartphone with advanced camera system and all-day battery life.",
    },
    {
      id: 14,
      name: "Laptop Stand",
      price: 45.99,
      originalPrice: 59.99,
      image: "/images/products/laptop-stand.png",
      category: "Electronics",
      rating: 4.3,
      reviews: 98,
      description: "Ergonomic laptop stand with adjustable height and cooling ventilation.",
    },
    {
      id: 15,
      name: "Water Bottle",
      price: 24.99,
      originalPrice: 34.99,
      image: "/images/products/water-bottle.png",
      category: "Sports",
      rating: 4.5,
      reviews: 167,
      description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours.",
    },
    {
      id: 16,
      name: "Sunglasses",
      price: 89.99,
      originalPrice: 119.99,
      image: "/images/products/sunglasses.png",
      category: "Fashion",
      rating: 4.2,
      reviews: 76,
      description: "Polarized sunglasses with UV protection and scratch-resistant lenses.",
    },
    {
      id: 17,
      name: "Tablet",
      price: 399.99,
      originalPrice: 499.99,
      image: "/images/products/tablet.png",
      category: "Electronics",
      rating: 4.6,
      reviews: 189,
      description: "High-performance tablet with stunning display and all-day battery life.",
    },
    {
      id: 18,
      name: "Plant Pot",
      price: 19.99,
      originalPrice: 29.99,
      image: "/images/products/plant-pot.png",
      category: "Home & Garden",
      rating: 4.1,
      reviews: 54,
      description: "Ceramic plant pot with drainage system and modern minimalist design.",
    },
    {
      id: 19,
      name: "Gaming Chair",
      price: 249.99,
      originalPrice: 299.99,
      image: "/images/products/gaming-chair.png",
      category: "Gaming",
      rating: 4.8,
      reviews: 145,
      description: "Ergonomic gaming chair with lumbar support and adjustable armrests.",
    },
    {
      id: 20,
      name: "Fitness Tracker",
      price: 129.99,
      originalPrice: 159.99,
      image: "/images/products/fitness-tracker.png",
      category: "Sports",
      rating: 4.4,
      reviews: 203,
      description: "Advanced fitness tracker with heart rate monitoring and sleep tracking.",
    },
  ]
  
  export const featuredProducts = products.slice(0, 8)
  
  export const getProductById = (id: number): Product | undefined => {
    return products.find((product) => product.id === id)
  }
  
  export const getProductsByCategory = (category: string): Product[] => {
    return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
  }
  